#include <trycatch.hpp>
#include <log.hpp>

extern const char *ERROR_CODE_TEXT[];

#define FOREACH_ERROR_CODE(ERROR_CODE) \
		ERROR_CODE(DUMMY_ERROR)\
		ERROR_CODE(ERROR_BC471_COMMTEST_FAILED)\
		ERROR_CODE(ERROR_BC471_SET_NAME_FAILED)\
		ERROR_CODE(ERROR_BC471_SET_PIN_FAILED)\
		ERROR_CODE(ERROR_BC471_SET_BAUD_FAILED)\
		ERROR_CODE(ERROR_BC471_COMMTEST_OK)\
		ERROR_CODE(ERROR_GENERIC)

#define GENERATE_ERROR_CODE(ERROR_CODE) ERROR_CODE,
#define GENERATE_ERROR_CODE_STRING(STRING) #STRING,

 typedef enum ERROR_CODE_ENUM
 {
  FOREACH_ERROR_CODE(GENERATE_ERROR_CODE)
 } ERROR_CODE;


#define MAKE_PRINTABLE_ERROR(x) SEGGER_RTT_printf(LOGGING_CHANNEL, "Error: %s [%s:%u]\r\n", ERROR_CODE_TEXT[x], __FUNCTION__, __LINE__)
